import 'package:flutter/material.dart';
import 'package:damd_trabalho_1/theme/Tokens.dart';

final ThemeData light = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: Tokens.primary500,
    onPrimary: Tokens.neutral950,
    primaryContainer: Tokens.primary100,
    onPrimaryContainer: Tokens.primary800,
    secondary: Tokens.neutral700,
    onSecondary: Tokens.neutral0,
    secondaryContainer: Tokens.neutral200,
    onSecondaryContainer: Tokens.neutral800,
    tertiary: Tokens.primary300,
    onTertiary: Tokens.primary950,
    tertiaryContainer: Tokens.primary50,
    onTertiaryContainer: Tokens.primary900,
    error: Colors.red.shade700,
    onError: Tokens.neutral0,
    errorContainer: Colors.red.shade200,
    onErrorContainer: Colors.red.shade900,
    background: Tokens.neutral50,
    onBackground: Tokens.neutral950,
    surface: Tokens.neutral100,
    onSurface: Tokens.neutral950,
    surfaceVariant: Tokens.neutral50,
    onSurfaceVariant: Tokens.neutral700,
    outline: Tokens.neutral900,
    outlineVariant: Tokens.neutral300,
    shadow: Tokens.neutral950.withOpacity(0.2),
    scrim: Tokens.neutral950.withOpacity(0.5),
    inverseSurface: Tokens.neutral950,
    onInverseSurface: Tokens.neutral0,
    inversePrimary: Tokens.primary200,
    surfaceTint: Tokens.primary500.withOpacity(0.1),
  ),
  textTheme: TextTheme(
    displayLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    displayMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    displaySmall: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    headlineLarge: TextStyle(fontSize: Tokens.fontSize24, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    headlineMedium: TextStyle(fontSize: Tokens.fontSize20, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    headlineSmall: TextStyle(fontSize: Tokens.fontSize16, fontWeight: FontWeight.bold, color: Tokens.neutral900),
    bodyLarge: TextStyle(fontSize: Tokens.fontSize16, color: Tokens.neutral800),
    bodyMedium: TextStyle(fontSize: Tokens.fontSize14, color: Tokens.neutral800),
    bodySmall: TextStyle(fontSize: Tokens.fontSize12, color: Tokens.neutral700),
  ),
  scaffoldBackgroundColor: Tokens.neutral50,
  appBarTheme: AppBarTheme(
    backgroundColor: Tokens.neutral50,
    foregroundColor: Tokens.neutral900,
    elevation: 0,
  ),
  snackBarTheme: const SnackBarThemeData(
    actionTextColor: Tokens.primary500,
    backgroundColor: Tokens.neutral0,
    contentTextStyle: TextStyle(color: Tokens.neutral950),
    elevation: 20,
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: Tokens.primary500,
      foregroundColor: Tokens.neutral0,
      padding: const EdgeInsets.symmetric(horizontal: Tokens.spacing16, vertical: Tokens.spacing12),
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(Tokens.radius8)),
    ),
  ),
  cardTheme: CardThemeData(
    color: Tokens.neutral0,
    elevation: 2,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(Tokens.radius12)),
    margin: const EdgeInsets.all(Tokens.spacing8),
  ),
);